---
# tasks file for lighthouse-role
- name: Lighthouse ----- Installing Git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Lighthouse ----- Downloading Lighthouse
  become: true
  git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
- name: Lighthouse ----- Creating lighthouse vector config
  become: true
  template:
    src: templates/lighthouse.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644