- name: Install nginx
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
- name: Start-nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
- name: Creating config
  become: true
  ansible.builtin.template:
    src: templates/nginx.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
- name: nginx-reload
  become: true
  ansible.builtin.command: nginx -s reload
  register: nginx_reload_output